### PR TITLE
Replace Active Support with barebones inflections

### PR DESCRIPTION
**Pull request by kaspth**
I can live with the half-broken implementation for now.

### CODE REVIEW

**Comment by Spone** [comment]
Hi @kaspth just to check: this means I have to use `persons.john_doe` instead of `people.john_doe` to access my `Person` model fixtures? Is there another way?

**Comment by kaspth** [comment]
@Spone oh this was a while back. `people.` should work out of the box, but if not you may need to call `register Person, as: :people` in something like `db/seeds/setup.rb`.

If you want you can also open up a discussion over on https://github.com/kaspth/oaken/discussions and we can talk through other setup issues.

**Comment by Spone** [comment]
@kaspth it did the trick! Thanks!

```rb
# db/seeds/setup.rb
register Person, as: :people
```

**Comment by kaspth** [comment]
awesome! 😄

**Pull request merged**
